# CLI tools
brew "antidote"
brew "bat"
brew "btop"
brew "claude-code"
brew "curl"
brew "doggo"
brew "duf"
brew "dust"
brew "fd"
brew "gh"
brew "git"
brew "gping"
brew "helm"
brew "httpie"
brew "jq"
brew "k9s"
brew "kubectx"
brew "kubernetes-cli"
brew "lsd"
brew "neovim"
brew "podman"
brew "procs"
brew "ripgrep"
brew "rsync"
brew "uv"
brew "watch"
brew "wget"
brew "zoxide"

# GNU tools
brew "coreutils"
brew "findutils"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "grep"

# Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"

# 1Password CLI (for git credential helper + SSH agent)
cask "1password-cli"

# Apps
cask "appcleaner"
cask "chatgpt"
cask "claude"
cask "cleanshot"
cask "firefox"
cask "google-chrome"
cask "ice"
cask "iina"
cask "iterm2"
cask "obsidian"
cask "perplexity"
cask "podman-desktop"
cask "vlc"

# VS Code extensions
vscode "charliermarsh.ruff"
vscode "christian-kohler.path-intellisense"
vscode "DavidAnson.vscode-markdownlint"
vscode "esbenp.prettier-vscode"
vscode "Gruntfuggly.todo-tree"
vscode "hashicorp.terraform"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.python"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "tamasfe.even-better-toml"
vscode "usernamehw.errorlens"
